# Generated by Django 6.0.4 on 2026-05-13 22:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_akku', '0003_servicio_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=150)),
                ('cuerpo', ckeditor.fields.RichTextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blog_images')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
